### ISSUE TITLE
Create front/backend for the donations search bar

### ISSUE THREAD

**Issue by JoshuaChou10** [JoshuaChou10/ICS4UO-project#11]
Allow user to search for donations

**Comment by AritroSaha10** [comment]
Just a quick update on this: I've set up the Algolia backend. The next step is creating a cron job script in the backend that syncs the data in Firebase with the Algolia index. After that, I will start working on adding the frontend part after we have the frontend somewhat setup.

**Comment by AritroSaha10** [comment]
Done 🎉🎉🎉
